# Generated by Django 5.1.6 on 2026-09-06 14:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouse', '0002_loading_loadingitem_vanstock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='raqam')),
                ('date', models.DateField(verbose_name='sana')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='summa')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_returns', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_returns', to='warehouse.warehouse', verbose_name='ombor')),
            ],
            options={
                'verbose_name': 'kunlik qaytarish',
                'verbose_name_plural': 'kunlik qaytarishlar',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='DailyReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='miqdor')),
                ('condition', models.CharField(choices=[('GOOD', 'Yaroqli'), ('DAMAGED', 'Shikastlangan'), ('EXPIRED', "Muddati o'tgan")], default='GOOD', max_length=10, verbose_name='holati')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='narx')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='summa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('daily_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dayclose.dailyreturn', verbose_name='qaytarish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_return_items', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'qaytarish qatori',
                'verbose_name_plural': 'qaytarish qatorlari',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DayClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('date', models.DateField(verbose_name='sana')),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('PENDING', 'Tasdiq kutilmoqda'), ('CLOSED', 'Yopilgan')], db_index=True, default='PENDING', max_length=10, verbose_name='holat')),
                ('loaded_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='yuklangan')),
                ('sold_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='sotilgan')),
                ('returned_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='qaytarilgan')),
                ('stock_difference_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='tovar farqi (dona)')),
                ('stock_difference_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='tovar farqi (summa)')),
                ('cash_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='naqd sotuv')),
                ('debt_collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='undirilgan qarz')),
                ('cash_expected', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='kutilgan naqd')),
                ('cash_handed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='topshirilgan naqd')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='manfiy = kamomad', max_digits=14, verbose_name='kassa farqi')),
                ('debt_given_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='qarzga berilgan')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='sotuvlar soni')),
                ('visits_count', models.PositiveIntegerField(default=0, verbose_name='tashriflar soni')),
                ('new_clients_count', models.PositiveIntegerField(default=0, verbose_name='yangi mijozlar')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='yopilgan vaqti')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yopdi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_closes', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
            ],
            options={
                'verbose_name': 'kun yopish',
                'verbose_name_plural': 'kun yopishlar',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='dailyreturn',
            name='day_close',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_returns', to='dayclose.dayclose', verbose_name='kun yopish'),
        ),
        migrations.CreateModel(
            name='CashHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('date', models.DateField(verbose_name='sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='summa')),
                ('confirmed', models.BooleanField(default=False, verbose_name='tasdiqlangan')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='handovers/', verbose_name='rasm')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_handovers', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim qabul qildi')),
                ('day_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_handovers', to='dayclose.dayclose', verbose_name='kun yopish')),
            ],
            options={
                'verbose_name': 'kassaga topshirish',
                'verbose_name_plural': 'kassaga topshirishlar',
                'ordering': ('-date',),
            },
        ),
        migrations.AddIndex(
            model_name='dayclose',
            index=models.Index(fields=['status', '-date'], name='dayclose_da_status_074885_idx'),
        ),
        migrations.AddConstraint(
            model_name='dayclose',
            constraint=models.UniqueConstraint(fields=('distributor', 'date'), name='uniq_dayclose_distributor_date'),
        ),
    ]
