# Generated by Django 5.1.6 on 2026-09-06 15:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayclose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayclose',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='xarajat (jami)'),
        ),
        migrations.AddField(
            model_name='dayclose',
            name='expense_approved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name="tasdiqlangan xarajat (qo'ldagi naqd)"),
        ),
        migrations.AddField(
            model_name='dayclose',
            name='wallet_balance_end',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='kun oxiridagi hamyon balansi'),
        ),
    ]
