# Generated by Django 5.1.6 on 2026-09-06 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('type', models.CharField(choices=[('sale.flagged', 'Belgilangan sotuv'), ('expense.limit_exceeded', 'Xarajat limiti oshdi'), ('expense.approved', 'Xarajat tasdiqlandi'), ('expense.rejected', 'Xarajat rad etildi'), ('cash.difference', 'Kassa farqi'), ('stock.low', 'Kam qoldiq'), ('loading.confirmed', 'Yuklama tasdiqlandi'), ('dayclose.submitted', 'Kun yopish yuborildi'), ('debt.overdue', "Qarz muddati o'tdi"), ('sync.conflict', 'Sinxronizatsiya ziddiyati'), ('general', 'Umumiy')], db_index=True, default='general', max_length=32, verbose_name='turi')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('body', models.CharField(blank=True, max_length=1000, verbose_name='matn')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name="qo'shimcha ma'lumot")),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="o'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="o'qilgan vaqti")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'bildirishnoma',
                'verbose_name_plural': 'bildirishnomalar',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
