# Generated by Django 5.1.6 on 2026-09-06 11:50

import apps.users.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='telefon')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH.')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super admin'), ('MANAGER', 'Menejer'), ('WAREHOUSE', 'Omborchi'), ('DISTRIBUTOR', 'Tarqatuvchi'), ('ACCOUNTANT', 'Buxgalter')], db_index=True, default='DISTRIBUTOR', max_length=20, verbose_name='rol')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='rasm')),
                ('passport_series', models.CharField(blank=True, max_length=20, verbose_name='passport seriyasi')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='ishga kirgan sana')),
                ('device_id', models.CharField(blank=True, max_length=128, verbose_name='qurilma ID')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='oxirgi faollik')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'foydalanuvchi',
                'verbose_name_plural': 'foydalanuvchilar',
                'ordering': ('full_name',),
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DistributorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, verbose_name='mashina raqami')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='asosiy maosh')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='komissiya foizi')),
                ('monthly_plan', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='oylik reja')),
                ('debt_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='qarz limiti')),
                ('can_sell_below_price', models.BooleanField(default=False, verbose_name='minimal narxdan past sotishga ruxsat')),
                ('daily_expense_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='kunlik xarajat limiti')),
                ('expenses_covered_by', models.CharField(choices=[('COMPANY', 'Kompaniya'), ('SALARY', 'Maoshdan')], default='COMPANY', max_length=10, verbose_name='xarajatni kim qoplaydi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarqatuvchi profili',
                'verbose_name_plural': 'tarqatuvchi profillari',
            },
        ),
    ]
