# Generated by Django 5.1.6 on 2026-09-08 04:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='delivery_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='yetkazib bergani uchun foiz'),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='order_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='zakaz olgani uchun foiz'),
        ),
        migrations.AlterField(
            model_name='distributorprofile',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Eski yagona foiz — order/delivery foizi 0 bo'lsa ishlatiladi", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='komissiya foizi (legacy)'),
        ),
    ]
