# Generated by Django 5.1.6 on 2026-09-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_websocketticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan"),
        ),
    ]
