# Generated by Django 5.2.17 on 2026-09-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_password_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super admin'), ('MANAGER', 'Menejer'), ('WAREHOUSE', 'Omborchi'), ('DISTRIBUTOR', 'Tarqatuvchi'), ('ACCOUNTANT', 'Buxgalter'), ('ORDER_TAKER', 'Zakaz oluvchi')], db_index=True, default='DISTRIBUTOR', max_length=20, verbose_name='rol'),
        ),
    ]
