# Generated by Django 5.2.17 on 2026-09-29 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_order_taker'),
        ('warehouse', '0006_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='warehouse.warehouse', verbose_name='ombor / filial'),
        ),
    ]
