# Generated by Django 5.1.6 on 2026-09-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super admin'), ('MANAGER', 'Menejer'), ('BRANCH_MANAGER', 'Filial rahbari'), ('WAREHOUSE', 'Omborchi'), ('DISTRIBUTOR', 'Tarqatuvchi'), ('ACCOUNTANT', 'Buxgalter'), ('ORDER_TAKER', 'Zakaz oluvchi')], db_index=True, default='DISTRIBUTOR', max_length=20, verbose_name='rol'),
        ),
    ]
