# Generated by Django 5.1.6 on 2026-09-06 12:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='raqam')),
                ('invoice_number', models.CharField(blank=True, max_length=64, verbose_name='nakladnoy raqami')),
                ('date', models.DateField(verbose_name='sana')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='umumiy summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="to'langan")),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='qarz')),
                ('source', models.CharField(choices=[('MANUAL', "Qo'lda"), ('SCAN', 'Naklit skani')], default='MANUAL', max_length=8, verbose_name='manba')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('CONFIRMED', 'Tasdiqlangan')], db_index=True, default='DRAFT', max_length=10, verbose_name='holat')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='tasdiqlangan vaqti')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'tovar qabuli',
                'verbose_name_plural': 'tovar qabullari',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='miqdor')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='dona narxi')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='summa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.product', verbose_name='mahsulot')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.purchase', verbose_name='qabul')),
            ],
            options={
                'verbose_name': 'qabul qatori',
                'verbose_name_plural': 'qabul qatorlari',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='INN / STIR')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'yetkazib beruvchi',
                'verbose_name_plural': 'yetkazib beruvchilar',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='warehouse.supplier', verbose_name='yetkazib beruvchi'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=128, verbose_name='nomi')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'ombor',
                'verbose_name_plural': 'omborlar',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='warehouse.warehouse', verbose_name='ombor'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('movement_type', models.CharField(choices=[('IN_PURCHASE', 'Kirim — xarid'), ('OUT_LOADING', 'Chiqim — yuklash'), ('IN_RETURN', 'Kirim — qaytarish'), ('OUT_SALE', 'Chiqim — sotuv'), ('ADJUSTMENT', 'Tuzatish (inventarizatsiya)'), ('WRITE_OFF', 'Hisobdan chiqarish (brak)'), ('TRANSFER', "Ko'chirish"), ('CORRECTION', 'Xatoni tuzatuvchi yozuv')], db_index=True, max_length=16, verbose_name='turi')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='miqdor (ishorali)')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='harakatdan keyingi qoldiq')),
                ('from_location', models.CharField(blank=True, max_length=128, verbose_name='qayerdan')),
                ('to_location', models.CharField(blank=True, max_length=128, verbose_name='qayerga')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='havola turi')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='havola ID')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product', verbose_name='mahsulot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='kim')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.warehouse', verbose_name='ombor')),
            ],
            options={
                'verbose_name': 'tovar harakati',
                'verbose_name_plural': 'tovar harakati jurnali',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['warehouse', 'product', '-created_at'], name='warehouse_s_warehou_e885f4_idx'), models.Index(fields=['reference_type', 'reference_id'], name='warehouse_s_referen_852b45_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='qoldiq')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='band qilingan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.product', verbose_name='mahsulot')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='warehouse.warehouse', verbose_name='ombor')),
            ],
            options={
                'verbose_name': 'qoldiq',
                'verbose_name_plural': 'qoldiqlar',
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'product'), name='uniq_stock_warehouse_product'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_non_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('supplier', 'invoice_number'), name='uniq_purchase_supplier_invoice'),
        ),
    ]
