# Generated by Django 5.1.6 on 2026-09-06 13:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='raqam')),
                ('date', models.DateField(verbose_name='sana')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('SENT', 'Yuborilgan'), ('CONFIRMED', 'Tasdiqlangan'), ('CLOSED', 'Yopilgan')], db_index=True, default='DRAFT', max_length=10, verbose_name='holat')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='umumiy summa')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='yuborilgan vaqti')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='tasdiqlangan vaqti')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loadings', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loadings', to='warehouse.warehouse', verbose_name='ombor')),
            ],
            options={
                'verbose_name': 'yuklama',
                'verbose_name_plural': 'yuklamalar',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LoadingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='narx')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='summa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('loading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.loading', verbose_name='yuklama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_items', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'yuklama qatori',
                'verbose_name_plural': 'yuklama qatorlari',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='VanStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='qoldiq')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_stocks', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_stocks', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': "mashina qoldig'i",
                'verbose_name_plural': 'mashina qoldiqlari',
                'ordering': ('product__name',),
            },
        ),
        migrations.AddIndex(
            model_name='loading',
            index=models.Index(fields=['distributor', '-date'], name='warehouse_l_distrib_3c2d9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vanstock',
            constraint=models.UniqueConstraint(fields=('distributor', 'product'), name='uniq_vanstock_distributor_product'),
        ),
        migrations.AddConstraint(
            model_name='vanstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='vanstock_quantity_non_negative'),
        ),
    ]
