# Generated by Django 5.1.6 on 2026-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_loading_loadingitem_vanstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN_PURCHASE', 'Kirim — xarid'), ('OUT_LOADING', 'Chiqim — yuklash'), ('IN_RETURN', 'Kirim — qaytarish'), ('OUT_SALE', 'Chiqim — sotuv'), ('ADJUSTMENT', 'Tuzatish (inventarizatsiya)'), ('WRITE_OFF', 'Hisobdan chiqarish (brak)'), ('TRANSFER', "Ko'chirish"), ('CORRECTION', 'Xatoni tuzatuvchi yozuv'), ('OPENING_BALANCE', "Boshlang'ich qoldiq")], db_index=True, max_length=16, verbose_name='turi'),
        ),
    ]
