# Generated by Django 5.2.17 on 2026-09-23 11:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_stockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='balans'),
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('date', models.DateField(verbose_name='sana')),
                ('transaction_type', models.CharField(choices=[('OPENING_BALANCE', "Boshlang'ich qoldiq (±)"), ('CORRECTION', 'Tuzatuvchi yozuv (±)')], db_index=True, max_length=16, verbose_name='turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='summa (ishorali)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='keyingi balans')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='warehouse.supplier', verbose_name='yetkazib beruvchi')),
            ],
            options={
                'verbose_name': "ta'minotchi tranzaksiyasi",
                'verbose_name_plural': "ta'minotchi tranzaksiyalari",
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['supplier', '-created_at'], name='warehouse_s_supplie_fc88dc_idx')],
            },
        ),
    ]
