# Generated by Django 5.2.17 on 2026-09-29 03:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage'),
        ('warehouse', '0004_supplier_balance_suppliertransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='raqam')),
                ('date', models.DateField(verbose_name='sana')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('CONFIRMED', 'Tasdiqlangan'), ('CANCELLED', 'Bekor qilingan')], db_index=True, default='DRAFT', max_length=10, verbose_name='holat')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='tasdiqlangan vaqti')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='kim tasdiqladi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='warehouse.warehouse', verbose_name='ombor')),
            ],
            options={
                'verbose_name': 'inventarizatsiya',
                'verbose_name_plural': 'inventarizatsiyalar',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('expected_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='hisobda')),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='haqiqiy')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='tannarx')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.inventorycount', verbose_name='inventarizatsiya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'inventarizatsiya qatori',
                'verbose_name_plural': 'inventarizatsiya qatorlari',
                'ordering': ('product__name',),
                'constraints': [models.UniqueConstraint(fields=('count', 'product'), name='uniq_inventory_item_product')],
            },
        ),
    ]
