# Generated by Django 5.2.17 on 2026-09-29 05:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage'),
        ('warehouse', '0005_inventory_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_branch',
            field=models.BooleanField(db_index=True, default=False, verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name="mas'ul"),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefon'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='raqam')),
                ('date', models.DateField(verbose_name='sana')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('SENT', "Yo'lda"), ('RECEIVED', 'Qabul qilingan'), ('CANCELLED', 'Bekor qilingan')], db_index=True, default='DRAFT', max_length=10, verbose_name='holat')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('receive_note', models.CharField(blank=True, max_length=255, verbose_name='qabul izohi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='yuborilgan vaqti')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='qabul vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouse.warehouse', verbose_name='qayerdan')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL, verbose_name='qabul qilgan')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_sent', to=settings.AUTH_USER_MODEL, verbose_name='yuborgan')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouse.warehouse', verbose_name='qayerga')),
            ],
            options={
                'verbose_name': "ko'chirish",
                'verbose_name_plural': "ko'chirishlar",
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name="jo'natilgan")),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='qabul qilingan')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='tannarx')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='catalog.product', verbose_name='mahsulot')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.transfer', verbose_name="ko'chirish")),
            ],
            options={
                'verbose_name': "ko'chirish qatori",
                'verbose_name_plural': "ko'chirish qatorlari",
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True), name='transfer_distinct_warehouses'),
        ),
        migrations.AddConstraint(
            model_name='transferitem',
            constraint=models.UniqueConstraint(fields=('transfer', 'product'), name='uniq_transfer_item_product'),
        ),
    ]
