# Generated by Django 5.1.6 on 2026-10-10 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_opening_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name="boshlang'ich qoldiq tasdiqlangan"),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='opening_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tasdiqlangan vaqt'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='opening_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_warehouse_openings', to=settings.AUTH_USER_MODEL, verbose_name='tasdiqlagan admin'),
        ),
    ]
