# Generated by Django 5.1.6 on 2026-10-10 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_branchprice'),
        ('warehouse', '0007_warehouse_is_opening_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='purchase_item_cost_price_gte_zero'),
        ),
    ]
