# Generated by Django 5.1.6 on 2026-09-06 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('action', models.CharField(max_length=64, verbose_name='harakat')),
                ('model_name', models.CharField(blank=True, max_length=128, verbose_name='model')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='obyekt ID')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name="o'zgarishlar")),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='qurilma / brauzer')),
            ],
            options={
                'verbose_name': 'audit yozuvi',
                'verbose_name_plural': 'audit jurnali',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='kalit')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='qiymat')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
            ],
            options={
                'verbose_name': 'sozlama',
                'verbose_name_plural': 'sozlamalar',
                'ordering': ('key',),
            },
        ),
    ]
