# Generated by Django 5.1.6 on 2026-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=16)),
                ('year', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'hujjat ketma-ketligi',
                'verbose_name_plural': 'hujjat ketma-ketliklari',
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='uniq_docseq_prefix_year')],
            },
        ),
    ]
