# Generated by Django 5.1.6 on 2026-09-08 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documentsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='nomi')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name="to'liq yuridik nomi")),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='STIR / INN')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='telefon')),
                ('bank_details', models.TextField(blank=True, verbose_name='bank rekvizitlari')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='rahbar F.I.SH.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='logotip')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='muhr (PNG, shaffof fon)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'kompaniya rekvizitlari',
                'verbose_name_plural': 'kompaniya rekvizitlari',
            },
        ),
    ]
