# Generated by Django 5.1.6 on 2026-09-29 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('device_id', models.CharField(blank=True, max_length=128, verbose_name='qurilma')),
                ('operations_count', models.PositiveIntegerField(default=0, verbose_name='operatsiyalar')),
                ('conflicts_count', models.PositiveIntegerField(default=0, verbose_name='konfliktlar')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='xatolar')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='davomiyligi (ms)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'sinxronizatsiya jurnali',
                'verbose_name_plural': 'sinxronizatsiya jurnali',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_synclo_user_id_c5a470_idx')],
            },
        ),
    ]
