# Generated by Django 5.1.6 on 2026-09-06 15:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dayclose', '0002_dayclose_expense_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nomi')),
                ('icon', models.CharField(blank=True, max_length=32, verbose_name='ikonka')),
                ('color', models.CharField(blank=True, max_length=16, verbose_name='rang')),
                ('requires_receipt', models.BooleanField(default=False, verbose_name='chek majburiy')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0 = limitsiz', max_digits=14, verbose_name='kunlik limit')),
                ('paid_by', models.CharField(choices=[('COMPANY', 'Kompaniya'), ('DISTRIBUTOR', 'Tarqatuvchi')], default='COMPANY', max_length=12, verbose_name="kim to'laydi")),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'xarajat kategoriyasi',
                'verbose_name_plural': 'xarajat kategoriyalari',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DistributorExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('date', models.DateField(verbose_name='sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='summa')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='chek rasmi')),
                ('receipt_scan_data', models.JSONField(blank=True, default=dict, verbose_name="chek OCR ma'lumoti")),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='uzunlik')),
                ('payment_source', models.CharField(choices=[('CASH_ON_HAND', "Qo'ldagi naqd"), ('OWN_MONEY', 'Shaxsiy pul'), ('COMPANY_CARD', 'Kompaniya kartasi')], default='CASH_ON_HAND', max_length=16, verbose_name="to'lov manbai")),
                ('status', models.CharField(choices=[('PENDING', 'Tasdiq kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], db_index=True, default='PENDING', max_length=10, verbose_name='holat')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='tasdiqlangan vaqti')),
                ('reject_reason', models.CharField(blank=True, max_length=255, verbose_name='rad sababi')),
                ('is_deductible', models.BooleanField(default=False, help_text="expenses_covered_by=SALARY bo'lsa", verbose_name='maoshdan ushlanadimi')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('is_synced', models.BooleanField(default=True, verbose_name='sinxronlangan')),
                ('device_time', models.DateTimeField(blank=True, null=True, verbose_name='qurilma vaqti')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim tasdiqladi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('day_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='dayclose.dayclose', verbose_name='kun yopish')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'xarajat',
                'verbose_name_plural': 'xarajatlar',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='litr')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='litr narxi')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='odometr')),
                ('station_name', models.CharField(blank=True, max_length=128, verbose_name='shoxobcha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_log', to='expenses.distributorexpense', verbose_name='xarajat')),
            ],
            options={
                'verbose_name': "yoqilg'i jurnali",
                'verbose_name_plural': "yoqilg'i jurnallari",
            },
        ),
        migrations.AddIndex(
            model_name='distributorexpense',
            index=models.Index(fields=['distributor', '-date'], name='expenses_di_distrib_3708f0_idx'),
        ),
        migrations.AddIndex(
            model_name='distributorexpense',
            index=models.Index(fields=['status'], name='expenses_di_status_f13668_idx'),
        ),
    ]
