# Generated by Django 5.1.6 on 2026-09-08 04:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productalias'),
        ('clients', '0001_initial'),
        ('warehouse', '0002_loading_loadingitem_vanstock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='raqam')),
                ('date', models.DateField(verbose_name='sana')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('PLACED', 'Berilgan'), ('APPROVED', 'Tasdiqlangan'), ('LOADED', 'Yuklamaga olindi'), ('DELIVERED', 'Yetkazildi'), ('PARTIALLY_DELIVERED', 'Qisman yetkazildi'), ('CANCELLED', 'Bekor qilindi')], db_index=True, default='DRAFT', max_length=20, verbose_name='holat')),
                ('payment_intent', models.CharField(blank=True, choices=[('NAQD', 'Naqd'), ('PLASTIK', 'Plastik karta'), ('OTKAZMA', "Bank o'tkazmasi"), ('QARZ', 'Qarzga'), ('ARALASH', 'Aralash')], max_length=10, verbose_name="to'lov niyati")),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='istalgan yetkazish sanasi')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='umumiy summa')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='mijoz tomonidagi UUID')),
                ('device_time', models.DateTimeField(blank=True, null=True, verbose_name='qurilma vaqti')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='bekor qilingan vaqti')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='bekor sababi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_to_deliver', to=settings.AUTH_USER_MODEL, verbose_name='yetkazuvchi')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client', verbose_name='mijoz')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('loading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='warehouse.loading', verbose_name='yuklama')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_taken', to=settings.AUTH_USER_MODEL, verbose_name='zakazni kim oldi')),
            ],
            options={
                'verbose_name': 'buyurtma',
                'verbose_name_plural': 'buyurtmalar',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='miqdor')),
                ('delivered_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='yetkazilgan miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='narx')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='summa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'buyurtma qatori',
                'verbose_name_plural': 'buyurtma qatorlari',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['taken_by', '-date'], name='orders_orde_taken_b_5b2b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_to', '-date'], name='orders_orde_assigne_8d211e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-date'], name='orders_orde_status_6a9c82_idx'),
        ),
    ]
