# Generated by Django 5.1.6 on 2026-09-06 18:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('period', models.DateField(help_text='oyning birinchi kuni (masalan 2026-09-01)', verbose_name='davr')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='sotuv summasi')),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='sof foyda')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='komissiya')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='asosiy maosh')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='bonus')),
                ('deduction_shortage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='tovar kamomadi ushlanmasi')),
                ('deduction_cash_diff', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='kassa farqi ushlanmasi')),
                ('deduction_expense', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='xarajat ushlanmasi')),
                ('reimbursement_expense', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='xarajat qaytarimi')),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='avans')),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='yakuniy summa')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('APPROVED', 'Tasdiqlangan'), ('PAID', "To'langan")], db_index=True, default='DRAFT', max_length=10, verbose_name='holat')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='tasdiqlangan vaqti')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="to'langan vaqti")),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='hisoblangan vaqti')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim tasdiqladi')),
                ('company_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.companyexpense', verbose_name='kompaniya xarajati')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
            ],
            options={
                'verbose_name': 'maosh',
                'verbose_name_plural': 'maoshlar',
                'ordering': ('-period', 'distributor__full_name'),
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('date', models.DateField(verbose_name='sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='summa')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('wallet_transaction_id', models.UUIDField(blank=True, null=True)),
                ('cash_transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='payroll.payroll', verbose_name='qaysi maoshda hisobga olindi')),
            ],
            options={
                'verbose_name': 'avans',
                'verbose_name_plural': 'avanslar',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('scope', models.CharField(choices=[('GLOBAL', 'Umumiy'), ('CATEGORY', 'Kategoriya'), ('PRODUCT', 'Mahsulot'), ('DISTRIBUTOR', 'Tarqatuvchi')], max_length=12, verbose_name='qamrov')),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='foiz')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='asos summa')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='komissiya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payroll', verbose_name='maosh')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_details', to='sales.saleitem', verbose_name='sotuv qatori')),
            ],
            options={
                'verbose_name': 'maosh tafsiloti',
                'verbose_name_plural': 'maosh tafsilotlari',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('scope', models.CharField(choices=[('GLOBAL', 'Umumiy'), ('CATEGORY', 'Kategoriya'), ('PRODUCT', 'Mahsulot'), ('DISTRIBUTOR', 'Tarqatuvchi')], db_index=True, default='GLOBAL', max_length=12, verbose_name='qamrov')),
                ('target_id', models.UUIDField(blank=True, help_text='CATEGORY→kategoriya, PRODUCT→mahsulot, DISTRIBUTOR→foydalanuvchi', null=True, verbose_name='obyekt ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='foiz')),
                ('valid_from', models.DateField(verbose_name='amal qiladi (dan)')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='amal qiladi (gacha)')),
                ('priority', models.IntegerField(default=0, help_text='Bir xil qamrovda kattasi yutadi', verbose_name='ustuvorlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'komissiya qoidasi',
                'verbose_name_plural': 'komissiya qoidalari',
                'ordering': ('-priority', '-created_at'),
                'indexes': [models.Index(fields=['scope', 'target_id', 'is_active'], name='payroll_com_scope_4d7a69_idx'), models.Index(fields=['valid_from', 'valid_to'], name='payroll_com_valid_f_a765d3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status', '-period'], name='payroll_pay_status_3b589d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('distributor', 'period'), name='uniq_payroll_distributor_period'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['distributor', '-date'], name='payroll_adv_distrib_8bb098_idx'),
        ),
    ]
