# Generated by Django 5.1.6 on 2026-09-08 04:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='delivery_commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='yetkazish komissiyasi'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='order_commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='zakaz komissiyasi'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='beneficiary',
            field=models.ForeignKey(blank=True, help_text='Odatda payroll.distributor bilan bir xil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kimga'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='role',
            field=models.CharField(choices=[('ORDER', 'Zakaz olgani'), ('DELIVERY', 'Yetkazib bergani')], db_index=True, default='DELIVERY', max_length=10, verbose_name='ish turi'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='komissiya (jami)'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='scope',
            field=models.CharField(blank=True, choices=[('GLOBAL', 'Umumiy'), ('CATEGORY', 'Kategoriya'), ('PRODUCT', 'Mahsulot'), ('DISTRIBUTOR', 'Tarqatuvchi')], default='', max_length=12, verbose_name='qamrov (legacy)'),
        ),
    ]
