# Generated by Django 5.1.6 on 2026-09-06 16:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nomi')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='balans')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'kassa',
                'verbose_name_plural': 'kassalar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('date', models.DateField(verbose_name='sana')),
                ('transaction_type', models.CharField(choices=[('HANDOVER_IN', 'Tarqatuvchidan naqd (+)'), ('OTHER_IN', 'Boshqa kirim (+)'), ('BANK_DEPOSIT', 'Bankka topshirildi (−)'), ('SUPPLIER_PAYMENT', "Yetkazib beruvchiga to'lov (−)"), ('COMPANY_EXPENSE', 'Kompaniya xarajati (−)'), ('OTHER_OUT', 'Boshqa chiqim (−)'), ('CORRECTION', 'Tuzatuvchi yozuv (±)')], db_index=True, max_length=20, verbose_name='turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='summa (ishorali)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='keyingi balans')),
                ('counterparty', models.CharField(blank=True, max_length=255, verbose_name='kontragent')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='havola turi')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='havola ID')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.cashaccount', verbose_name='kassa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'kassa tranzaksiyasi',
                'verbose_name_plural': 'kassa tranzaksiyalari',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('date', models.DateField(verbose_name='sana')),
                ('category', models.CharField(choices=[('RENT', 'Ijara'), ('SALARY', 'Maosh'), ('UTILITIES', "Kommunal to'lovlar"), ('TRANSPORT', 'Transport'), ('MARKETING', 'Marketing'), ('TAX', 'Soliq'), ('OTHER', 'Boshqa')], default='OTHER', max_length=16, verbose_name='kategoriya')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='summa')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('paid_from_cash', models.BooleanField(default=True, help_text="True bo'lsa kassa balansidan chiqadi", verbose_name="kassadan to'landimi")),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='company_receipts/', verbose_name='hujjat')),
                ('cash_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_expense', to='finance.cashtransaction', verbose_name='kassa yozuvi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'kompaniya xarajati',
                'verbose_name_plural': 'kompaniya xarajatlari',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['account', '-created_at'], name='finance_cas_account_7a6be4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='finance_cas_referen_275ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='companyexpense',
            index=models.Index(fields=['category', '-date'], name='finance_com_categor_a65137_idx'),
        ),
    ]
