# Generated by Django 5.1.6 on 2026-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('HANDOVER_IN', 'Tarqatuvchidan naqd (+)'), ('OTHER_IN', 'Boshqa kirim (+)'), ('BANK_DEPOSIT', 'Bankka topshirildi (−)'), ('SUPPLIER_PAYMENT', "Yetkazib beruvchiga to'lov (−)"), ('COMPANY_EXPENSE', 'Kompaniya xarajati (−)'), ('OTHER_OUT', 'Boshqa chiqim (−)'), ('CORRECTION', 'Tuzatuvchi yozuv (±)'), ('OPENING_BALANCE', "Boshlang'ich qoldiq (±)")], db_index=True, max_length=20, verbose_name='turi'),
        ),
    ]
