# Generated by Django 5.1.6 on 2026-09-29 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_cashtransaction_transaction_type'),
        ('warehouse', '0006_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_account', to='warehouse.warehouse', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='companyexpense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_expenses', to='warehouse.warehouse', verbose_name='filial'),
        ),
    ]
