# Generated by Django 5.1.6 on 2026-09-06 12:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'brend',
                'verbose_name_plural': 'brendlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=128, verbose_name='nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name="bo'lim")),
            ],
            options={
                'verbose_name': 'kategoriya',
                'verbose_name_plural': 'kategoriyalar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='artikul (SKU)')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='shtrix-kod')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='rasm')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='tannarx')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='optom narx')),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='chakana narx')),
                ('min_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='minimal narx')),
                ('pack_quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='qadoqdagi soni')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='komissiya foizi')),
                ('min_stock_alert', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='kam qoldiq ogohlantirishi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='faol')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='kategoriya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'mahsulot',
                'verbose_name_plural': 'mahsulotlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='tannarx')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='optom narx')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='chakana narx')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='minimal narx')),
                ('effective_from', models.DateTimeField(verbose_name='amal qila boshlagan sana')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='sababi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'narx tarixi',
                'verbose_name_plural': 'narx tarixi',
                'ordering': ('-effective_from',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nomi')),
                ('short_name', models.CharField(max_length=16, verbose_name='qisqa nomi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': "o'lchov birligi",
                'verbose_name_plural': "o'lchov birliklari",
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.unit', verbose_name="o'lchov birligi"),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'name'], name='catalog_pro_is_acti_d8c282_idx'),
        ),
    ]
