# Generated by Django 5.1.6 on 2026-09-06 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouse', '0002_loading_loadingitem_vanstock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('alias_text', models.CharField(max_length=255, verbose_name='nom')),
                ('hit_count', models.PositiveIntegerField(default=1, verbose_name='ishlatilgan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.product', verbose_name='mahsulot')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_aliases', to='warehouse.supplier', verbose_name='yetkazib beruvchi')),
            ],
            options={
                'verbose_name': 'mahsulot nomi (alias)',
                'verbose_name_plural': 'mahsulot nomlari (alias)',
                'ordering': ('-hit_count',),
                'constraints': [models.UniqueConstraint(fields=('product', 'alias_text', 'supplier'), name='uniq_alias_product_text_supplier')],
            },
        ),
    ]
