# Generated by Django 5.1.6 on 2026-09-08 04:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='rasm')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/gallery/thumb/', verbose_name='eskiz')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('is_primary', models.BooleanField(default=False, verbose_name='asosiy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'mahsulot rasmi',
                'verbose_name_plural': 'mahsulot rasmlari',
                'ordering': ('sort_order', 'created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('product',), name='uniq_primary_image_per_product')],
            },
        ),
    ]
