# Generated by Django 5.1.6 on 2026-09-29 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage'),
        ('warehouse', '0006_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='optom narx')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='chakana narx')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='minimal narx')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='warehouse.warehouse', verbose_name='filial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'filial narxi',
                'verbose_name_plural': 'filial narxlari',
                'ordering': ('product__name',),
                'constraints': [models.UniqueConstraint(fields=('branch', 'product'), name='uniq_branch_price_per_product')],
            },
        ),
    ]
