# Generated by Django 5.1.6 on 2026-09-06 15:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='balans')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
            ],
            options={
                'verbose_name': 'hamyon',
                'verbose_name_plural': 'hamyonlar',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('date', models.DateField(verbose_name='sana')),
                ('transaction_type', models.CharField(choices=[('SALE_CASH', 'Naqd sotuv (+)'), ('DEBT_COLLECTED', 'Undirilgan qarz (+)'), ('EXPENSE', 'Xarajat (−)'), ('HANDOVER', 'Kassaga topshirildi (−)'), ('ADVANCE', 'Avans (+)'), ('CORRECTION', 'Tuzatuvchi yozuv (±)')], db_index=True, max_length=16, verbose_name='turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='summa (ishorali)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='keyingi balans')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='havola turi')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='havola ID')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.distributorwallet', verbose_name='hamyon')),
            ],
            options={
                'verbose_name': 'hamyon tranzaksiyasi',
                'verbose_name_plural': 'hamyon tranzaksiyalari',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallet_wall_wallet__ccf672_idx'), models.Index(fields=['reference_type', 'reference_id'], name='wallet_wall_referen_a44abf_idx')],
            },
        ),
    ]
