# Generated by Django 5.1.6 on 2026-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE_CASH', 'Naqd sotuv (+)'), ('DEBT_COLLECTED', 'Undirilgan qarz (+)'), ('EXPENSE', 'Xarajat (−)'), ('HANDOVER', 'Kassaga topshirildi (−)'), ('ADVANCE', 'Avans (+)'), ('CORRECTION', 'Tuzatuvchi yozuv (±)'), ('OPENING_BALANCE', "Boshlang'ich balans (±)")], db_index=True, max_length=16, verbose_name='turi'),
        ),
    ]
