# Generated by Django 5.1.6 on 2026-09-06 17:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productalias'),
        ('warehouse', '0002_loading_loadingitem_vanstock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('scan_type', models.CharField(choices=[('INVOICE', 'Nakladnoy'), ('RECEIPT', 'Chek')], default='INVOICE', max_length=10, verbose_name='turi')),
                ('status', models.CharField(choices=[('UPLOADED', 'Yuklandi'), ('PROCESSING', 'Qayta ishlanmoqda'), ('NEEDS_REVIEW', 'Tekshirish kerak'), ('CONFIRMED', 'Tasdiqlangan'), ('FAILED', 'Xato'), ('CANCELLED', 'Bekor qilingan')], db_index=True, default='UPLOADED', max_length=14, verbose_name='holat')),
                ('detected_invoice_number', models.CharField(blank=True, max_length=64, verbose_name='aniqlangan raqam')),
                ('detected_date', models.DateField(blank=True, null=True, verbose_name='aniqlangan sana')),
                ('detected_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='aniqlangan jami')),
                ('detected_supplier_name', models.CharField(blank=True, max_length=255, verbose_name='aniqlangan yetkazuvchi')),
                ('raw_text', models.TextField(blank=True, verbose_name='xom matn')),
                ('ai_response', models.JSONField(blank=True, default=dict, verbose_name='AI javobi')),
                ('confidence', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4, verbose_name='ishonch')),
                ('provider', models.CharField(blank=True, choices=[('claude', 'Claude vision'), ('tesseract', 'Tesseract'), ('mock', 'Mock (sinov)')], max_length=12, verbose_name='provayder')),
                ('image_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='rasm hashi')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='tokenlar')),
                ('cost_usd', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=8, verbose_name='xarajat (USD)')),
                ('processing_time_ms', models.PositiveIntegerField(default=0, verbose_name='vaqt (ms)')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='xato')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='tasdiqlangan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_scan', to='warehouse.purchase', verbose_name='qabul')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_scans', to='warehouse.supplier', verbose_name='yetkazib beruvchi')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_scans', to=settings.AUTH_USER_MODEL, verbose_name='kim yukladi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_scans', to='warehouse.warehouse', verbose_name='ombor')),
            ],
            options={
                'verbose_name': 'naklit skani',
                'verbose_name_plural': 'naklit skanlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceScanLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='qator raqami')),
                ('raw_name', models.CharField(blank=True, max_length=500, verbose_name='nomi (xom)')),
                ('raw_quantity', models.CharField(blank=True, max_length=64, verbose_name='miqdor (xom)')),
                ('raw_unit', models.CharField(blank=True, max_length=64, verbose_name='birlik (xom)')),
                ('raw_price', models.CharField(blank=True, max_length=64, verbose_name='narx (xom)')),
                ('raw_amount', models.CharField(blank=True, max_length=64, verbose_name='summa (xom)')),
                ('match_confidence', models.PositiveIntegerField(default=0, verbose_name='moslik %')),
                ('match_status', models.CharField(choices=[('EXACT', 'Aniq moslik'), ('FUZZY', "O'xshash (tasdiq kerak)"), ('NEW', 'Yangi mahsulot'), ('UNMATCHED', 'Topilmadi')], default='UNMATCHED', max_length=10, verbose_name='moslik holati')),
                ('final_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='yakuniy miqdor')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='yakuniy narx')),
                ('low_confidence', models.BooleanField(default=False, verbose_name='past ishonch')),
                ('was_corrected', models.BooleanField(default=False, verbose_name='tuzatilgan')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='tasdiqlangan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('final_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='yakuniy mahsulot')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='topilgan mahsulot')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ocr.invoicescan', verbose_name='skan')),
            ],
            options={
                'verbose_name': 'skan qatori',
                'verbose_name_plural': 'skan qatorlari',
                'ordering': ('line_number',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceScanPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('image', models.ImageField(upload_to='invoice_scans/', verbose_name='rasm')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='invoice_scans/processed/', verbose_name='qayta ishlangan rasm')),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='varaq raqami')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr.invoicescan', verbose_name='skan')),
            ],
            options={
                'verbose_name': "skan varag'i",
                'verbose_name_plural': 'skan varaqlari',
                'ordering': ('page_number',),
            },
        ),
        migrations.AddIndex(
            model_name='invoicescan',
            index=models.Index(fields=['status', '-created_at'], name='ocr_invoice_status_bf5a3a_idx'),
        ),
    ]
