# Generated by Django 5.1.6 on 2026-09-06 12:43

import apps.clients.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=128, verbose_name='nomi')),
                ('days_of_week', models.JSONField(blank=True, default=list, validators=[apps.clients.models._validate_weekdays], verbose_name='hafta kunlari')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
            ],
            options={
                'verbose_name': 'marshrut',
                'verbose_name_plural': 'marshrutlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('name', models.CharField(max_length=255, verbose_name="do'kon nomi")),
                ('owner_name', models.CharField(blank=True, max_length=255, verbose_name='egasining ismi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name="qo'shimcha telefon")),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='uzunlik')),
                ('client_type', models.CharField(choices=[('SHOP', "Do'kon"), ('MARKET', 'Bozor'), ('SUPERMARKET', 'Supermarket'), ('PHARMACY', 'Dorixona'), ('OTHER', 'Boshqa')], default='SHOP', max_length=16, verbose_name='turi')),
                ('debt_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='qarz limiti')),
                ('current_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Denormalized — DebtPayment/Sale orqali yangilanadi', max_digits=14, verbose_name='joriy qarz')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='INN / STIR')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='rasm')),
                ('is_blocked', models.BooleanField(db_index=True, default=False, verbose_name='bloklangan')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.route', verbose_name='marshrut')),
            ],
            options={
                'verbose_name': 'mijoz',
                'verbose_name_plural': 'mijozlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClientVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('checked_in_at', models.DateTimeField(verbose_name='tashrif vaqti')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='uzunlik')),
                ('result', models.CharField(choices=[('SOTUV', "Sotuv bo'ldi"), ('SOTUVSIZ', 'Sotuvsiz'), ('YOPIQ', 'Yopiq edi')], max_length=10, verbose_name='natija')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visits/', verbose_name='rasm')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='mijoz tomonidagi UUID')),
                ('device_time', models.DateTimeField(blank=True, null=True, verbose_name='qurilma vaqti')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clients.client', verbose_name='mijoz')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_visits', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
            ],
            options={
                'verbose_name': 'tashrif',
                'verbose_name_plural': 'tashriflar',
                'ordering': ('-checked_in_at',),
                'indexes': [models.Index(fields=['distributor', '-checked_in_at'], name='clients_cli_distrib_6adf37_idx'), models.Index(fields=['client', '-checked_in_at'], name='clients_cli_client__bde1cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['route', 'name'], name='clients_cli_route_i_0c284b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_blocked'], name='clients_cli_is_bloc_b8907d_idx'),
        ),
    ]
