# Generated by Django 5.1.6 on 2026-09-29 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_order_taker'),
        ('warehouse', '0006_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='warehouse.warehouse', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='route',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='warehouse.warehouse', verbose_name='filial'),
        ),
    ]
