# Generated by Django 5.2.17 on 2026-09-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_branch_route_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='route_order',
            field=models.PositiveIntegerField(default=0, verbose_name='marshrutdagi tartib'),
        ),
    ]
