# Generated by Django 5.1.6 on 2026-09-06 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('code', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='kod')),
                ('expires_at', models.DateTimeField(verbose_name='amal qilish muddati')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='ishlatilgan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': "Telegram bog'lash kodi",
                'verbose_name_plural': "Telegram bog'lash kodlari",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramMessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('chat_id', models.CharField(max_length=64, verbose_name='chat ID')),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=3, verbose_name="yo'nalish")),
                ('text', models.TextField(blank=True, verbose_name='matn')),
                ('ok', models.BooleanField(default=True, verbose_name='muvaffaqiyatli')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='xato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram xabar',
                'verbose_name_plural': 'Telegram xabarlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
