# Generated by Django 5.1

import base64
import hashlib

from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.db import migrations, models


def _cipher(secret):
    digest = hashlib.sha256(secret.encode()).digest()
    return Fernet(base64.urlsafe_b64encode(digest))


def reencrypt_existing_credentials(apps, schema_editor):
    credential_model = apps.get_model("telegram_bot", "TelegramBotCredential")
    version = settings.TELEGRAM_CREDENTIAL_KEY_VERSION
    keys = dict(settings.TELEGRAM_CREDENTIAL_KEYS)
    try:
        current_cipher = _cipher(keys[version])
    except KeyError as exc:
        raise RuntimeError(
            f"Telegram credential key version {version!r} is not configured"
        ) from exc
    legacy_cipher = _cipher(keys.get("legacy", settings.SECRET_KEY))

    for credential in credential_model.objects.iterator():
        try:
            token = legacy_cipher.decrypt(
                credential.encrypted_token.encode()
            )
            webhook_secret = (
                legacy_cipher.decrypt(
                    credential.encrypted_webhook_secret.encode()
                )
                if credential.encrypted_webhook_secret
                else b""
            )
        except (InvalidToken, ValueError) as exc:
            raise RuntimeError(
                "Telegram credential could not be re-encrypted; "
                "configure the previous Django key as the 'legacy' key."
            ) from exc

        credential.encrypted_token = current_cipher.encrypt(token).decode()
        credential.encrypted_webhook_secret = (
            current_cipher.encrypt(webhook_secret).decode()
            if webhook_secret
            else ""
        )
        credential.encryption_key_version = version
        credential.save(
            update_fields=[
                "encrypted_token",
                "encrypted_webhook_secret",
                "encryption_key_version",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0003_telegrambotcredential_encrypted_webhook_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambotcredential",
            name="encryption_key_version",
            field=models.CharField(
                default="legacy",
                max_length=32,
                verbose_name="shifrlash kaliti versiyasi",
            ),
        ),
        migrations.RunPython(
            reencrypt_existing_credentials,
            migrations.RunPython.noop,
        ),
    ]