# Generated by Django 5.1.6 on 2026-09-06 14:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name="to'langan")),
                ('remaining', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='qoldiq')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='muddat')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('PARTIAL', "Qisman to'langan"), ('PAID', "To'langan"), ('OVERDUE', "Muddati o'tgan")], db_index=True, default='ACTIVE', max_length=10, verbose_name='holat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='clients.client', verbose_name='mijoz')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
            ],
            options={
                'verbose_name': 'qarz',
                'verbose_name_plural': 'qarzlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='summa')),
                ('payment_type', models.CharField(choices=[('NAQD', 'Naqd'), ('PLASTIK', 'Plastik karta'), ('OTKAZMA', "Bank o'tkazmasi"), ('QARZ', 'Qarzga'), ('ARALASH', 'Aralash')], default='NAQD', max_length=10, verbose_name="to'lov turi")),
                ('date', models.DateField(verbose_name='sana')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_payments', to=settings.AUTH_USER_MODEL, verbose_name="kim yig'di")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.debt', verbose_name='qarz')),
            ],
            options={
                'verbose_name': "qarz to'lovi",
                'verbose_name_plural': "qarz to'lovlari",
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='raqam')),
                ('date', models.DateField(verbose_name='sana')),
                ('payment_type', models.CharField(choices=[('NAQD', 'Naqd'), ('PLASTIK', 'Plastik karta'), ('OTKAZMA', "Bank o'tkazmasi"), ('QARZ', 'Qarzga'), ('ARALASH', 'Aralash')], max_length=10, verbose_name="to'lov turi")),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='umumiy summa')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='chegirma')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name="to'langan")),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='qarz')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='qarz muddati')),
                ('status', models.CharField(choices=[('COMPLETED', 'Yakunlangan'), ('FLAGGED', "Belgilangan (ko'rib chiqilsin)"), ('CONFLICT', 'Ziddiyat (admin hal qilsin)'), ('CANCELLED', 'Bekor qilingan')], db_index=True, default='COMPLETED', max_length=10, verbose_name='holat')),
                ('flagged', models.BooleanField(db_index=True, default=False, verbose_name='belgilangan')),
                ('flag_reason', models.CharField(blank=True, max_length=255, verbose_name='belgilash sababi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='uzunlik')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='mijoz tomonidagi UUID')),
                ('is_synced', models.BooleanField(default=True, verbose_name='sinxronlangan')),
                ('device_time', models.DateTimeField(blank=True, null=True, verbose_name='qurilma vaqti')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='imzo')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='bekor qilingan vaqti')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='clients.client', verbose_name='mijoz')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
            ],
            options={
                'verbose_name': 'sotuv',
                'verbose_name_plural': 'sotuvlar',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='sales.sale', verbose_name='sotuv'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='narx')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='tannarx (snapshot)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='chegirma %')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='summa')),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='foyda')),
                ('below_min_price', models.BooleanField(default=False, verbose_name='minimal narxdan past')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product', verbose_name='mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='sotuv')),
            ],
            options={
                'verbose_name': 'sotuv qatori',
                'verbose_name_plural': 'sotuv qatorlari',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='raqam')),
                ('date', models.DateField(verbose_name='sana')),
                ('reason', models.CharField(choices=[('BRAK', 'Brak'), ('MUDDAT', "Muddati o'tgan"), ('KELISHMOVCHILIK', 'Kelishmovchilik')], max_length=16, verbose_name='sababi')),
                ('restock', models.BooleanField(default=True, help_text='Brak odatda qaytmaydi', verbose_name="mashina qoldig'iga qaytsinmi")),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='summa')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='izoh')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='clients.client', verbose_name='mijoz')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to=settings.AUTH_USER_MODEL, verbose_name='tarqatuvchi')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.sale', verbose_name='asl sotuv')),
            ],
            options={
                'verbose_name': 'sotuv qaytarishi',
                'verbose_name_plural': 'sotuv qaytarishlari',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='miqdor')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='narx')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='summa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim yaratdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='catalog.product', verbose_name='mahsulot')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salereturn', verbose_name='qaytarish')),
            ],
            options={
                'verbose_name': 'qaytarish qatori',
                'verbose_name_plural': 'qaytarish qatorlari',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['distributor', '-date'], name='sales_sale_distrib_c2fe6e_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['client', '-date'], name='sales_sale_client__96f79b_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'flagged'], name='sales_sale_status_5b83b0_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['client', 'status'], name='sales_debt_client__dc829c_idx'),
        ),
    ]
