# Generated by Django 5.1.6 on 2026-09-07 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['date'], name='sales_debtp_date_897836_idx'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['collected_by', '-date'], name='sales_debtp_collect_9edcfe_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date', 'status'], name='sales_sale_date_0a90cc_idx'),
        ),
    ]
