# Generated by Django 5.1.6 on 2026-09-29 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_order'),
        ('warehouse', '0006_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.warehouse', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.warehouse', verbose_name='filial'),
        ),
    ]
